feh --bg-center /home/samba/tumblr_md5wq9cXSa1qe7ty5o1_.jpg
#
#tumblr_mb9ky2OYuv1qzcd3bo1_.png
#tumblr_mbjd37atPl1qb30dwo1_.jpg
#tumblr_mcmm7oYCkQ1qa5504o1_.gif
#tumblr_mcnd60fSFK1ruq4xfo1_.jpg
#tumblr_mco0lbu6Sg1rwft4xo1_.jpg
#tumblr_mcow6gU2Js1r1w416o1_.jpg
#tumblr_mcs8d6Acup1qzleu4o1_.jpg
#tumblr_mcs8gn2BvW1qzleu4o1_.jpg
#tumblr_mcsh6kkUgv1rsdlkxo1_.jpg
#tumblr_mcsnebtmOc1qzo3c9o1_.jpg
#tumblr_mcuovfsJth1qzo3c9o1_.jpg
#tumblr_mcvbp1dGNO1qziwcjo1_.jpg
#tumblr_mcvqxtNCMM1rsp1lio1_.jpg
#tumblr_mcwf758AMI1qa9omho1_.jpg
#tumblr_mcxfwbDtxD1ql2pkjo1_.jpg
#tumblr_md3a5k5Ao61qk442ao1_.gif
#tumblr_md3amry2ib1rfdjd5o1_.jpg
#tumblr_md3mfq9yGd1qcflzio1_.jpg
#tumblr_md4nup78ll1qc54cio1_.jpg
#tumblr_md5b84J5jf1rwjkkso1_.gif
#tumblr_md5ec4lDqT1qb6t6wo1_.jpg
#tumblr_md5mhktzfT1qz4dkmo1_.jpg
#tumblr_md5wq9cXSa1qe7ty5o1_.jpg
#tumblr_md6j8ddUZY1qzezhmo1_.jpg
#tumblr_md6v0vOH1w1qzljvuo1_.jpg
#tumblr_md7fl2iNNv1qzo3c9o1_.jpg

mlterm &
mlterm &
mlterm &
xclock &
